# -*- coding: utf-8 -*-
"""Project Python 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16da3GrJDNxCRRJ1zyzofAOueMs2EpLDH
"""

from tabulate import tabulate

# Class
class Transaction():
  def __init__(self):
      self.keranjang = list()

  def add_item(self):
    """
    Metode add_item berfungsi untuk menambahkan nama, jumlah, harga dari item yang di input

    Input berupa :
    nama_item = nama dalam bentuk string
    jumlah_item = jumlah dalam bentuk interger
    harga_per_item = harga dalam bentuk interger

    Output berupa:
    Tabel yang isinya berupa input dari yang sudah dimasukkan dan ada total harga
    """
    try:
      nama_item = input('Masukkan nama item :')
      nama_item = nama_item.lower()
      jumlah_item = int(input('Masukkan jumlah item :'))
      harga_per_item = int(input('Masukkan harga per item :'))
      total_harga = jumlah_item * harga_per_item
      self.keranjang.append([nama_item, int(jumlah_item), int(harga_per_item), total_harga])
      self.tabel()
        #print(self.keranjang)
    except ValueError:
      print('Jumlah Item dan Harga per Item harus dalam bentuk angka')

  def update_nama_item(self):
    """
    Metode update_nama_item berfungsi untuk mengupdate nama item yang sudah ada pada list

    input :
    nama_item = nama item yang ingin diganti
    nama_item_baru = nama item baru

    output :
    nama item sudah terupdate dengan yang baru
    """
    try:
      if self.keranjang != []:
        nama_item = input("Masukan nama barang yang ingin diganti : ")
        nama_item = nama_item.lower()
        nama_item_baru = input('Masukkan nama barang baru : ')
        nama_item_baru = nama_item_baru.lower()
        for nama in self.keranjang:
          if nama[0] == nama_item:
            nama[0] = nama_item_baru
        self.tabel()
      else:
        print("Keranjang anda kosong")
    except ValueError:
      print("Nama barang yang anda masukkan salah")

  def update_jumlah_item(self):
    """
    Metode update_jumlah_item berfungsi untuk update jumlah barang pada list

    input:
    nama_item = nama item yang jumlahnya ingin diganti
    jumlah_item_baru = jumlah item yang diinginkan

    output:
    jumlah barang dan total harga sudah terganti
    """
    try:
      nama_item = input("Masukan nama barang yang ingin diganti jumlahnya : ")
      nama_item = nama_item.lower()
      jumlah_item_baru = int(input('Masukkan jumlah item barang baru : '))
      for nama in self.keranjang:
        if nama[0] == nama_item:
          nama[1] = int(jumlah_item_baru)
          total_harga_baru = jumlah_item_baru * nama[2]
          nama[3] = total_harga_baru
        #elif nama[0] != nama_item:
          #print("Barang yang anda inputkan tidak ada")
      self.tabel()
    except ValueError:
      print("Jumlah barang yang anda masukkan harus dalam bentuk angka")
    

  def update_harga_item(self):
    """
    Metode update_harga_item berfungsi untuk mengupdate harga item

    input :
    nama_item = nama item yang harganya ingin diganti
    harga_baru = harga baru yang diinginkan

    output :
    harga barang dan total harga sudah terganti dengan yang baru
    """
    try:
      nama_item = input("Masukan nama barang yang ingin diganti harganya : ")
      nama_item = nama_item.lower()
      harga_baru = int(input('Masukkan harga item barang baru : '))
      for nama in self.keranjang:
        if nama[0] == nama_item:
          nama[2] = int(harga_baru)
          total_harga_baru = harga_baru * nama[1]
          nama[3] = total_harga_baru
        #elif nama[0] != nama_item:
          #print("Barang yang anda inputkan tidak ada")
      self.tabel()
        #print(self.keranjang)
    except ValueError:
      print("Harga barang yang anda masukkan harus dalam bentuk angka")

  def delete_item(self):
    """
    Metode delete_item untuk menghapus salah satu item pada list

    input : 
    nama_item = nama item yang ingin dihapus

    ouput :
    seluruh elemen dari item tersebut sudah terhapus    
    """
    try:
      nama_item = input("Masukkan nama barang yang anda ingin hapus :")
      for nama in self.keranjang:
        if nama[0] == nama_item:
          self.keranjang.remove(nama)
      self.tabel()
    except ValueError:
      print("Nama barang yang anda masukkan salah atau tidak ada")

  def reset_transaction(self):
    """
    Metode reset_transaction berfungsi untuk menghapus seluruh isi dari tabel
    """
    self.keranjang.clear()
    print("Seluruh barang di keranjang sudah anda hapus")
    self.tabel()
  
  def check_order(self):
    """
    Metode check_order berfungsi untuk memastikan type data sudah benar
    """
    for item in self.keranjang:
      nama_item = item[0]
      jumlah_item = item[1]
      harga_per_item = item[2]
    if type(nama_item) == str and type(jumlah_item) == int and type(harga_per_item) == int:
      print('Pemesanan sudah benar')
    else:
      print('Terdapat kesalahan pada inputan anda')
    self.tabel()

  def total_price(self):
    """
    Metode total_price berfungsi untuk menghitung total harga dari seluruh barang dan diskonnya
    """
    total_harga_akhir = 0
    for item in self.keranjang:
      total_harga_akhir += item[1] * item[2]
    if total_harga_akhir >= 200_000:
      diskon =  0.05
    elif total_harga_akhir >= 300_000:
      diskon = 0.08
    elif total_harga_akhir >= 300_000:
      diskon = 0.1
    else:
      diskon = 0
    self.tabel()
    harga_diskon = total_harga_akhir * diskon
    total_harga_akhir = total_harga_akhir - harga_diskon
    print(f"Belanja anda mendapatkan diskon sebesar Rp.{harga_diskon}. \nTotal harga yang harus dibayarkan adalah Rp.{total_harga_akhir}")

  def tabel(self):
    """
    Metode tabel berfungsi membuat tabel untuk list yang berisi item yang diinput
    """
    total_keranjang = self.keranjang
    header_tabel = [ "Nama Item", "Jumlah Item", "Harga Per Item", "Total Harga"]
    print(tabulate(total_keranjang, headers = header_tabel , tablefmt = "fancy_grid"))

# object transaction
trnsct_123 = Transaction()

# interface dari super cashier
while True:
  print('='*40)
  print("Selamat Datang Di Pacmann Super Cashier")
  print('='*40)
  print("Pilih perintah yang ingin anda jalankan \n",
        "1. Tambahkan Item \n",
        "2. Update Nama Item \n",
        "3. Update Jumlah Item \n",
        "4. Update Harga Item \n",
        "5. Delete Item \n",
        "6. Reset Transaction \n",
        "7. Check Order \n",
        "8. Total Harga \n",
        "9. Keluar")
  opsi_menu = int(input("Masukkan nomor perintah yang ingin anda jalankan : "))

  if opsi_menu == 1:
    trnsct_123.add_item()
    opsi_tambah = input("Apakah anda ingin menambah barang lagi (y/n) : ")
    opsi_tambah = opsi_tambah.lower()
    if opsi_tambah == 'y':
      trnsct_123.add_item()
    elif opsi_tambah == 'n':
      pass
    else:
      print("Masukkan perintah y/n")
  elif opsi_menu == 2:
    trnsct_123.tabel()
    trnsct_123.update_nama_item()
  elif opsi_menu == 3:
    trnsct_123.tabel()
    trnsct_123.update_jumlah_item()
  elif opsi_menu == 4:
    trnsct_123.tabel()
    trnsct_123.update_harga_item()
  elif opsi_menu == 5:
    opsi_delete = input("Apakah anda yakin ingin menghapus satu item (y/n)?")
    opsi_delete = opsi_delete.lower()
    if opsi_delete == 'y':
      trnsct_123.delete_item()
    elif opsi_delete == 'n':
      pass
    else:
      print("Masukkan perintah y/n")
  elif opsi_menu == 6:
    opsi_reset = input("Apakah anda yakin ingin reset transaksi (y/n)?")
    opsi_reset = opsi_reset.lower()
    if opsi_reset == 'y':
      trnsct_123.reset_transaction()
    elif opsi_reset == 'n':
      pass
    else:
      print("Masukkan perintah y/n")
  elif opsi_menu == 7:
    trnsct_123.check_order()
  elif opsi_menu == 8:
    trnsct_123.total_price()
  elif opsi_menu == 9:
    opsi_keluar = input("Apakah anda ingin keluar dari kasir (y/n) : ")
    opsi_keluar = opsi_keluar.lower()
    if opsi_keluar == 'y':
      trnsct_123.tabel()
      print("Terima kasih telah belanja di Pacmann Super Cashier")
      break
    elif opsi_keluar == 'n':
      pass
    else:
      print("Masukkan perintah y/n")